name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Configure Git
        run: |
          git config --global user.email "harsh.yadav262002@gmail.com"
          git config --global user.name "Harsh262002"

      - name: Add HF remote & fetch
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Remove existing 'hf' remote if present, then add with token for auth
          git remote remove hf || true
          git remote add hf https://Harsh262002:$HF_TOKEN@huggingface.co/spaces/Harsh262002/Rag_llm
          git fetch hf main

      - name: Merge hf/main preferring local changes (auto-resolve)
        # This merge will automatically keep your GitHub repo's versions when conflicts occur.
        run: |
          git merge --allow-unrelated-histories hf/main -X ours -m "Merge HF remote (prefer local)"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://Harsh262002:$HF_TOKEN@huggingface.co/spaces/Harsh262002/Rag_llm main
